DFE-Digital/search-and-compare-api

- .gitignore
- .vscode/launch.json
- .vscode/tasks.json
- SearchAndCompareApi.sln
- src/api/Controllers/UcasController.cs
- src/api/DatabaseAccess/CourseDbContext.cs
- src/api/Migrations/20180427164638_CourseModColumn.Designer.cs
- src/api/Migrations/20180427164638_CourseModColumn.cs
- src/api/Properties/launchSettings.json
- src/api/SearchAndCompareApi.csproj
- src/api/Startup.cs
- src/api/UcasSettings.cs
- src/api/appsettings.json
- src/domain/Client/ISearchAndCompareApi.cs
- src/domain/Client/SearchAndCompareApi.cs
- src/domain/Models/Course.cs
- src/domain/SearchAndCompareDomain.csproj
- tests/Integration.Tests/DatabaseAccess/CourseDbContextIntegrationBase.cs
- tests/Integration.Tests/DatabaseAccess/CourseDbContextIntegrationTests.cs
- tests/Integration.Tests/UcasLink/UcasCourseDbContextIntegrationTests.cs
Aside from the modifier which is currently hard-coded, this PR provides the ability to:
* get a new sessionId from the UCAS site
* build a URL for a course on the UCAS site (which will only be valid till the session expires)
Once this is merged and the nuget package updated we'll do a PR for the [UI project branch](https://github.com/DFE-Digital/search-and-compare-ui/commits/ucas-link) that makes use of this.
-----
This code is not yet well factored etc, but is a usable increment which can then be improved upon.
Feedback on the style of the PR welcome as we want to improve our balance of raw coding speed versus wider team interactions.
> Add UCAS link builder to search api

- src/api/Controllers/CoursesController.cs
- src/api/Controllers/UcasController.cs
- src/api/DatabaseAccess/CourseDbContext.cs
- src/api/DatabaseAccess/ICourseDbContext.cs
- src/domain/Client/IHttpClient.cs
- src/domain/Client/ISearchAndCompareApi.cs
- src/domain/Client/SearchAndCompareApi.cs
- src/domain/SearchAndCompareDomain.csproj
- tests/Integration.Tests/DatabaseAccess/CourseDbContextIntegrationTests.cs
- tests/Unit.Tests/Client/SearchAndCompareApi.Tests.cs
https://trello.com/c/NyS5Xcy3/51-persistent-urls-in-search-and-compare-using-course-code
Change UCAS-URL and Course details endpoints in API to accept course codes and find (case-insensitively) the matching course.
Bump API Client version number as this is a breaking change
Optionally instantiate S+C API client with a wrapper around HttpClient to make unit testing possible.
See tests and refer to corresponding UI pull request
> use (case insensitive) course codes in S+C URLs

- src/api/Controllers/CoursesController.cs
When pubbing a course a null provider can cause it to throw expection
Skip provider that are null
> Fixed null issues on importer

- src/api/Controllers/CoursesController.cs
- tests/Integration.Tests/Controllers/CoursesController.Tests.cs
We want to use subjects as reference data, ie. don't have them overridden when we re-import courses from Manage Courses
Preserve subjects analogously to how we preserve location
> preserve subjects across imports

- .vscode/launch.json
- src/api/Controllers/CoursesController.cs
- tests/Integration.Tests/Controllers/CoursesController.Tests.cs
- tests/Integration.Tests/Controllers/SaveSingleCourse_CoursesController.Tests.cs
- Eliminated a case where Locations/Subjects are added twice
- Allow for large payloads
- Allow absence of Provider and Campus Locations (some are genuinely unknown)
> Various fixes to the publish process

- src/api/Controllers/CoursesController.cs
- src/api/DatabaseAccess/CourseDbContext.cs
- tests/Integration.Tests/Controllers/CoursesController.Tests.cs
- tests/Integration.Tests/Controllers/SaveSingleCourse_CoursesController.Tests.cs
InvalidOperationException
"The entity of type 'Course' is sharing the table 'course' with entities of type 'Salary', but there is no entity of this type with the same key value that has been marked as 'Added'. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the key values."
Fix the above exception
Uncomment the fix to see exception
> Ef core issues

- src/api/Migrations/20180926122323_SimplifySubjectFundingModel.Designer.cs
- src/api/Migrations/20180926122323_SimplifySubjectFundingModel.cs
- src/domain/Models/SubjectFunding.cs
https://trello.com/c/qGLbomUM/363-mock-up-the-process-for-financial-incentives-updates
There is no longer a distinction between grades for bursary funds, so we
remove the columns that had captured that distinction.
> Remove unused fields in SubjectFunding

- src/api/Controllers/CoursesController.cs
https://trello.com/c/i2nx7BPC/401-sort-searching-by-training-provider-to-put-the-provider-first-followed-by-providers-they-accredit#
> When there is a search query, put provider ahead of accredited matches

- src/api/Controllers/CoursesController.cs
When users filter by providers ascending or descending, we should still order the subjects in alphabetical order.
A simple LINQ (?) query update.
I don't know how to test this, if someone could give a hand, happy to pair.
> Change order of search results when searched by provider

- src/api/DatabaseAccess/CourseDbContext.cs
- tests/Integration.Tests/Controllers/SaveSingleCourse_CoursesController.Tests.cs
When updating a course in api then viewing it in ui, it bombs out due to dupes for course section descriptions.
As well as dupe listing of campuses.
Fixed when updating a course its related collection items needs to loaded as well otherwise there is dupes in db.
> Compounding errors caused by dupes

- src/api/Controllers/CoursesController.cs
- src/domain/Filters/Enums/QualificationOption.cs
- src/domain/Filters/QueryFilter.cs
- src/domain/SearchAndCompareDomain.csproj
Shipping
The courses list is a get request so we need to serialise things into
a query string. However Lists are not supported at the moment.
To fix the fact that consequently, the qualification filter options got
dropped between API and UI, we use a bitmap instead.
> Fix course query serialisation

- src/api/Controllers/CoursesController.cs
- src/domain/Client/HttpClientWrapper.cs
- src/domain/Client/IHttpClient.cs
- src/domain/Client/ISearchAndCompareApi.cs
- src/domain/Client/SearchAndCompareApi.cs
- src/domain/SearchAndCompareDomain.csproj
- tests/Integration.Tests/Controllers/SaveSingleCourse_CoursesController.Tests.cs
- tests/Unit.Tests/Client/SearchAndCompareApi.Tests.cs
Publish courses when org enrichment is published 
- change save course to a HTTP PUT to api/courses
- increase request size limit
- accept a list of courses rather than a single course
> SaveCourse can now support multiple courses

- README.md
- src/domain/Client/HttpClientWrapper.cs
- src/domain/Client/SearchAndCompareApi.cs
- src/domain/Client/SearchAndCompareApiException.cs
- src/domain/SearchAndCompareDomain.csproj
- tests/Unit.Tests/Client/HttpClientWrapperTests.cs
- tests/Unit.Tests/Client/SearchAndCompareApi.Tests.cs
Throw dedicated exception.
As the `SearchAndCompareApi` class is shared it needs to capture and throw its own exception.
Throwing it's own exception helps to exposes and highlight to the caller that is trying to connect to `SearchAndCompareApi`
For `Developers` to realise without a doubt that the `SearchAndCompareApi` failed due to connectivity or config.
For `Application Insights` to able to show the dependencies failed to connect to `SearchAndCompareApi`
For dependencies such as:
`SearchAndCompareUI` to have a better way of handling the fact that `SearchAndCompareApi` is down/out of action.
`ManageCourseApi` to have a better way of handling the fact that `SearchAndCompareApi` is down/out of action.
Throw dedicated exception
> Added exception throwing on the search and compare api client

- src/api/DatabaseAccess/CourseDbContext.cs
- tests/Integration.Tests/DatabaseAccess/CourseDbContextIntegrationTests.cs
Zendesk: We had an issue that a provider with a smaller number of courses
was drowned out by providers with more courses. Since they had a short name,
no text search could be formed to return this provider in the 5 suggestions.  
This changes selection logic to say that if an exact match is available,
show this as the first result.
see tests
> Provider search prefers exact matches

- src/api/DatabaseAccess/CourseDbContext.cs
- src/api/Migrations/20181006050158_AddDistanceAddress.Designer.cs
- src/api/Migrations/20181006050158_AddDistanceAddress.cs
- src/domain/Models/Course.cs
- src/domain/SearchAndCompareDomain.csproj
- tests/Integration.Tests/DatabaseAccess/CourseDbContextIntegrationTests.cs
When a user searches by location, we match on the closest location but show the default provider address, causing confusion. So we want to show the address we matched on in the UI
Introduces a new field `DistanceAddress` to course and update the location queries to set it to the matching address at query-time.
Uses the same trick as for `Distance` to ensure no corresponding column is generated.
See test - note that DbContext caches results so fields that are populated ad-hoc such as `Distance` and `DistanceAddress` will always be the same even if you change search parameters. For that reason, the test needs to get a fresh context for each query.
> add distance address

- src/api/DatabaseAccess/CourseDbContext.cs
- tests/Integration.Tests/DatabaseAccess/CourseDbContextIntegrationTests.cs
There is a requirement to search by Ucas provider code on the Search By Location page.
https://trello.com/c/RHCRbSz8/431-search-by-provider-code-on-location-search-page
There is now an extra step in the query in the SuggestProviders() method. It now searches the provider code field as well as the provider name field.
> Changed query

- src/api/Controllers/CoursesController.cs
- src/api/DatabaseAccess/CourseDbContext.cs
Errors in prod when crawled because of bad links, causing noise in exception logs
Cope with missing data
For some reason errors in prod are already 404s, so visible behaviour isn't actually different.
> Don't throw when a course isn't found, 404 instead

- src/domain/Client/HttpClientWrapper.cs
The HttpWrapper class was created to handle exceptions when making requests to the Api. Any exceptions would result in a "Service Down" page being shown in the ui.
However when the api returned an internal error such as when the database is down then this was not handled and a non-styled error page was shown in the ui.
> HttpWrapper now handles internal errors

- src/api/Middleware/BearerTokenApiKeyHandler.cs
To try and figure out if the 404s seen on prod are anything to do with this bit of code.
> Switch to 401 for api-key auth failures

- src/api/Controllers/CoursesController.cs
The removal happens within a transaction and is followed by a re-add,
but there's a two minute pause between that and the next message.
To avoid giving someone heart-failure add some more context to the
message.
> Don't terrify the admin with a scary log message

- src/api/DatabaseAccess/CourseDbContext.cs
- tests/Integration.Tests/Controllers/SaveSingleCourse_CoursesController.Tests.cs
This is part of the story to search by SEN courses. Here is the card:
https://trello.com/c/dehAp9dq/574-search-by-send-courses 
The flag wasn't being set on import and this PR fixes the bug
> mapped sen courses flag plus test

- src/geocoder/LocationRequester.cs
- src/geocoder/Program.cs
- tests/Integration.Tests/Geocoder/LocationRequester.Tests.cs
**Note a failure is a failure, as well as partial failure is still a failure, hiding a failure is still a failure, so do not be a failure by hiding a failure, that is such a failure**
No one looks at the logs so no one knows that there is a location that has failed to geocode.
Success is no longer a guarantee to denote a unresolved geo coding.
Added additional logging
Added telemetry to denote error for failures for failed geo coding
Fixed the geo coder to be take in account lack of LastGeocodedUtc
Amended to denote that its a failure via exit code based on count of failures,
> Geocoding webjob

- src/api/DatabaseAccess/CourseDbContext.cs
- src/api/Migrations/20181213160201_ClearOrphanedCampusRecords.Designer.cs
- src/api/Migrations/20181213160201_ClearOrphanedCampusRecords.cs
- tests/Integration.Tests/Controllers/SaveSingleCourse_CoursesController.Tests.cs
On publishing a course all of the existing campus records are left in an orphaned state ie the course id is set to null. Here is the card for this:
https://trello.com/c/PV6njHQJ/785-multiple-campus-records-created-on-publish
Added a cascading delete to the context model builder.
Fixed test that would have revealed this issue if the assertions had been correct.
if you want to run this and see for yourself then:
1) Drop your local SearchAndCompare database
2) Change to the master branch for the SearchAndCompare api solution
3) Fire up the SearchAndCompare api (point to the local db)
4) Fire up manage course api and ui.
5) Publish a course, make a change and publish it again
6) Run this query on the SearchAndCompare api database "select * from campus;"
7) Notice there are campus records with …
> Fix orphaned campus records on publish

- .travis.yml
Deploy to prod isn't working. Prod3 isn't needed at the moment so unblock deploy by reverting the prod3 travis config.
Tried to fix it but ran into duplicate prod3 error.
Revert prod3 addition
> Kill prod3

- src/api/DatabaseAccess/CourseDbContext.cs
- tests/Integration.Tests/DatabaseAccess/CourseDbContextIntegrationTests.cs
A 500 is return when there is a trailing backslash and the end of a search string.
Here is the trello card:
https://trello.com/c/gPYhnnBz/700-error-for-trailing-slash-in-provider-name-search
A concern was raised of a potential security issue around sql injection possibility in this block of code.
However on further reading I am satisfied this is not the case as we are using parameters for the query and also using the full text search functionality in postgres that transforms the query string into search parameters. 
Filter out any backslashes in the query parameter
> Remove backslash in query plus tests

- src/api/Controllers/CoursesController.cs
- tests/Integration.Tests/Controllers/CoursesController.Tests.cs
- tests/Integration.Tests/Controllers/Pub.Tests.cs
- tests/Integration.Tests/Controllers/SaveSingleCourse_CoursesController.Tests.cs
Previous failures dropped 100% and ~10% of courses due to failures in import/manage courses. We have already prevented a 100% drop but smaller failures aren't protected against cascading from manage to find.
We could do this on the sending side but it seems more robust to do it here.
This PR doesn't cover how to configure acceptable / expected ranges. It raises issues around how to handle big expected spikes, and what it means to manage good/bad ratios.
I'm not 100% convinced by this change at the moment in terms of protecting against failure vs the overhead of constantly maintaining the boundaries and the cost of false positives (partly in terms of the numbing effect of too many false positives)
Proof of concept circuit breaker logic, not tested yet. Throws if outside limits, this will …
> [1032] Circuit breaker for preventing massive change in course count

- src/api/Startup.cs
This was breaking the synchronise from publish to search and compare.
It seems there's been a change in the dotnet runtime that caused this to
start failing. LocationRequester was a singleton depending on the scoped
dbcontext service which actually doesn't make sense from a scoping point
of view.
> System.InvalidOperationException: Cannot consume scoped service
> 'GovUk.Education.SearchAndCompare.Api.DatabaseAccess.ICourseDbContext'
> from singleton
> 'GovUk.Education.SearchAndCompare.Geocoder.ILocationRequester'.
By making the geocoder use the same scope rule as the dbcontext they now
line up and this stops failing.
> [1579] Fix dependency injection for geocoder

- src/api/Controllers/CoursesController.cs
- src/api/Helpers/CoursesDiffDetails.cs
- tests/Unit.Tests/CoursesDiffDetailsTests.cs
Additional info for when bulk uploading courses
Before the trip log it and send a postcard to logger
where x is  `[ProviderCode, CourseCode]`
where y is `total of added courses`
where z is `total of removed courses`
`CircuitBreaker Diff: [Removed:, [x,...]`
`CircuitBreaker Diff: [Added:, [x,...]`
`CircuitBreaker Diff: [Summary:, [[Added: y], [Removed: z]]]`
> [1581] Added additional logging

- azure/template.json
Enable App Service Logs for the service.
Add a resource deployment to the apps ARM template that references the App Service Log building block.
> Enable App Service Logs for the service

- src/api/DatabaseAccess/CourseDbContext.cs
- tests/Integration.Tests/DatabaseAccess/CourseDbContextIntegrationTests.cs
Providers were noticing that their names should appear higher when searching for their name directly
Prioritize partial matching at the start of the string
> [xxxx] Proritise providers starting with query
