.vscode/launch.json
src/api/Controllers/CoursesController.cs
src/api/Properties/launchSettings.json
src/domain/Client/ISearchAndCompareApi.cs
src/domain/Client/SearchAndCompareApi.cs
src/domain/Data/TotalCountResult.cs
src/domain/SearchAndCompareDomain.csproj

Get the total course in order to support suggested search for UI
Related 
https://dfedigital.atlassian.net/browse/BATSA-217

Total count for courses

---

.travis.yml

Update the travis.yaml file to deploy to the azure instances after build.
The username and site are configured in the yaml file, and the password is defined in an environment variable within travis.

Add azure_web_apps travis configuration

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
LICENSE

Add License and Github Templates as per `managing-courses-X` repos

Be kind to github

---

src/api/Program.cs
src/api/Startup.cs

As per https://github.com/DFE-Digital/manage-courses-api/pull/127

Log streaming

---

README.md
src/api/Controllers/CoursesController.cs
src/api/DatabaseAccess/CourseDbContext.cs
src/api/DatabaseAccess/ICourseDbContext.cs
src/api/Middleware/ApiTokenAuthAttribute.cs
src/api/Middleware/BearerTokenApiKeyDefaults.cs
src/api/Middleware/BearerTokenApiKeyExtensions.cs
src/api/Middleware/BearerTokenApiKeyHandler.cs
src/api/Middleware/BearerTokenApiKeyOptions.cs
src/api/Middleware/HttpRequestExtensions.cs
src/api/SearchAndCompareApi.csproj
src/api/Startup.cs
src/domain/Client/HttpClientWrapper.cs
src/domain/Client/IHttpClient.cs
src/domain/Client/ISearchAndCompareApi.cs
src/domain/Client/SearchAndCompareApi.cs
src/domain/Models/Course.cs
src/domain/SearchAndCompareDomain.csproj
tests/Integration.Tests/Controllers/CoursesController.Tests.cs
tests/Unit.Tests/Client/HttpClientWrapperTests.cs
tests/Unit.Tests/Client/SearchAndCompareApi.Tests.cs

https://trello.com/c/Py1dedyJ/265-publish-a-single-course-to-search-via-a-json-endpoint
The ability to publish courses via an authenticated api key endpoint

Search pub

---

src/api/Middleware/ApplicationBuilderSecurityExtensions.cs
src/api/Startup.cs

Add security headers for production

security headers for production

---

src/api/Controllers/CoursesController.cs

Based on the extract of existing courses using https://github.com/DFE-Digital/search-and-compare-api/tree/lossless_export_json to extract the courses and republishing it
Default subject area if none is given
Switch to that branch and use a database that has existing data to extract the data
https://github.com/DFE-Digital/search-and-compare-api/tree/lossless_export_json 
Then switch back to this branch and publish the courses

Default subject area

---

src/api/Controllers/CoursesController.cs
tests/Integration.Tests/Controllers/CoursesController.Tests.cs

Pub expectations
Its no pub if it throws exception

Pub exceptions

---

src/api/DatabaseAccess/CourseDbContext.cs

UI needs to show fundings
Expose fundings from ef core

Added funding to subject areas subjects ef core

---

src/api/Controllers/CoursesController.cs
src/domain/Filters/Enums/QualificationOption.cs
src/domain/Filters/QueryFilter.cs
src/domain/SearchAndCompareDomain.csproj

Added qualification options for the query filter
Removed pgce and qts bool values

Added qualification options for the query filter

---

src/api/Controllers/CoursesController.cs

Allow for qualification filter to be multiple-value

---

src/api/Controllers/CoursesController.cs

I've reformatted this file every time I try and solve the bug I'm looking at and each time I have to do it again because master keeps moving on :-)
So I'm doing the reformat as it's own PR to get it into master!

Reformat code

---

src/api/DatabaseAccess/CourseDbContext.cs

It's a calculated field
Got in the way of an earlier attempt at the results thing

Don't map distance

---

src/api/DatabaseAccess/CourseDbContext.cs
src/api/Middleware/BearerTokenApiKeyHandler.cs
src/domain/SearchAndCompareDomain.csproj
src/geocoder/LocationRequester.cs
src/geocoder/SearchAndCompareGeocoder.csproj
tests/Integration.Tests/Controllers/SaveSingleCourse_CoursesController.Tests.cs
tests/Integration.Tests/Geocoder/LocationRequester.Tests.cs
tests/Unit.Tests/Client/HttpClientWrapperTests.cs

Solve all the warnings raised during build

---

src/api/Controllers/CoursesController.cs

To avoid temporary loss of all courses. Which we decided we didn't like.
Tested locally with an exception in the middle, left data in previous state as expected.
No longer temporarily has zero courses in while running.

Wrap delete/add in a db transaction

---

src/api/Migrations/20181018120742_[VacStatus].Designer.cs
src/api/Migrations/20181018120742_[VacStatus].cs
src/domain/Models/Campus.cs
src/domain/Models/Course.cs
src/domain/SearchAndCompareDomain.csproj

There is a requirement to pull vac status into search and compare.
Here is the PR: https://trello.com/c/uRcCqSlF/485-publish-per-course-vacancy-info-to-search
This pr creates the new db fields

Use vac status

---

src/api/Controllers/CoursesController.cs
src/api/DatabaseAccess/CourseDbContext.cs
src/domain/Filters/QueryFilter.cs

This is part of the story to push vac_status through on publish.
Here's the PR: https://trello.com/c/uRcCqSlF/485-publish-per-course-vacancy-info-to-search

Added vac_status to the fields to be saved

---

src/api/SearchAndCompareApi.csproj
src/geocoder/SearchAndCompareGeocoder.csproj
tests/SearchAndCompareApi.Tests.csproj

Amended Microsoft.AspNetCore.All to use version 2.1.5
Amended Microsoft.EntityFrameworkCore to use version 2.1.4
Amended Npgsql.EntityFrameworkCore.PostgreSQL to use version 2.1.2
Amended Microsoft.EntityFrameworkCore.Design to use version 2.1.4
Amended Microsoft.EntityFrameworkCore.Sqlite to use version 2.1.4

potential security vulnerabilities in your dependencies

---

src/api/Program.cs

Prod is on fire
https://stackoverflow.com/questions/29518365/how-to-get-error-details-of-an-asp-net-5-app-deployed-on-azure-websites/29524042#29524042

Log errors during startup

---

src/api/Startup.cs

Prod app failing to start due to pg connection issues

Kill off migrations in startup

---

src/api/SearchAndCompareApi.csproj
src/geocoder/SearchAndCompareGeocoder.csproj
tests/SearchAndCompareApi.Tests.csproj

Revert "Amended Microsoft.AspNetCore.All to use version 2.1.5"

---

src/api/Middleware/BearerTokenApiKeyHandler.cs

override has since been changed to be the async variant

Remove outdated comment

---

src/api/EnvConfigConnectionStringBuilder.cs
src/api/SearchAndCompareApi.csproj
src/api/Startup.cs
src/geocoder/SearchAndCompareGeocoder.csproj
tests/SearchAndCompareApi.Tests.csproj

https://trello.com/c/yQcy9ENb/18-bring-master-staging-and-production-code-branches-back-inline

Bring dev in line with production

---

src/api/Middleware/BearerTokenApiKeyHandler.cs

Whoops. Had forgotten the previous PR was aimed at prod branch.
Unmerge https://github.com/DFE-Digital/search-and-compare-api/pull/94 till it's been past the other layers

Accidental merge revert

---

src/api/app_offline.htm.example

The offline page has relative URLs which are broken.
Stop using <base> tag because it's confusing even though it leads to less duplication.

Update offline page

---

src/api/Startup.cs

As per https://github.com/DFE-Digital/manage-courses-api/pull/229

Include migration error in log message & log to AI

---

src/api/Controllers/CoursesController.cs
tests/Integration.Tests/DatabaseAccess/CourseDbContextIntegrationBase.cs

Slightly more urgent because of prod issues and having to shunt around search db.
This will re-enable our ability to bring it back to consistency.
Follow on to https://github.com/DFE-Digital/manage-courses-api/pull/233
Blocking prod releases as this fixes a regression that we haven't released yet.
Retry compatible logic for transaction.

Fix bulk import with retry+transaction

---

src/api/Controllers/CoursesController.cs

This deals with the table statistics breaking, which has led to extremely
poor query performance in the past.
Add a `VACUUM ANALYZE` instruction at the end of a bulk-course import
Absolutely clueless on how and wether to test this specific change, advice welcome

Add a `VACUUM ANALYZE` instruction at the end of a bulk-course import

---

src/api/DatabaseAccess/CourseDbContext.cs
tests/Integration.Tests/DatabaseAccess/CourseDbContextIntegrationTests.cs

This is to simplify data migrations, such as subject renames
Subjects that don't map any courses are no longer shown in the subject selector
See test

Don't show empty subjects in the subject list

---

.travis.yml

Deploy to prod failed
https://travis-ci.org/DFE-Digital/search-and-compare-api/builds/477288533
```
Already up to date!
HEAD detached at cfcd4a7
nothing to commit, working tree clean
Dropped refs/stash@{0} (4570a1f4638b6c2c077b13fe9555de22111655a4)
Script failed with status 127
failed to deploy
```
Separate the prod & prod3 deploys.

Fixup prod3 deploy

---

.travis.yml

Fixed the deployment user with an escape on $

Deployment user update

---

src/api/Controllers/CoursesController.cs
src/api/Startup.cs
src/domain/Models/Enums/IncludesPgce.cs
tests/Integration.Tests/Controllers/CoursesController.Tests.cs
tests/Integration.Tests/Controllers/SaveSingleCourse_CoursesController.Tests.cs

This is the story to refactor/rename the IncludesPgce enum. Here is the card:
https://trello.com/c/SNklTJVj/686-rename-includespgce-enum-values-refactoring
Not sure if the requires a version bump.

name change complete

---

src/api/Startup.cs

Revert over-zealous rename

---

azure-pipelines.yml
azure/template.json

Geocoder WebJob is missing from API
Add build task to yml
Add new AS and ASP for Geocoder including required Google key

Add geocoder

---

README.md
azure/template.json
src/api/Program.cs
src/api/SearchAndCompareApi.csproj

As per https://github.com/DFE-Digital/search-and-compare-ui/pull/332

[1168] Sentry integration

---

azure/template.json

The arm template become malformed after a recent change
Re add the missing } to the parameters block
Ensure that the template can be parsed

Add missing bracket to param block

---

azure/template.json

Vsts
Added vsts related items for the circuit breaker course limit
https://github.com/DFE-Digital/search-and-compare-api/pull/132

[1032] Added vsts related items for the circuit breaker course limit

---

azure/template.json

Add resource deployment to ensure ASP outbound IP's are added to the relevant PostgreSQL firewall rules
- Add firewall rule resource deployment for API and Worker ASP

Add firewall rule resource

---

azure/template.json

Add ability to change size and instance count through ARM template
Add params for size and instance count
Add params to ASP resource

Add size and instance params

---

src/api/.tool-versions

Add asdf tool versioning

---

azure/template.json

Add `CIRCUIT_BREAKER_COURSE_LIMIT` property in web app settings

2526-add circuit breaker in appsettings
